
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myqvyjegmxtgvusnohsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cXZ5amVnbXh0Z3Z1c25vaHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzkwMjQsImV4cCI6MjA2MzQxNTAyNH0.FD4hoDB6sUQIQMCFNAcWzuUNZYJI4vtOSRJkVKymA3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
